package edu.kit.pse.bdhkw.server.controller;

import org.hibernate.Session;

import edu.kit.pse.bdhkw.server.communication.Request;
import edu.kit.pse.bdhkw.server.communication.Response;

/**
 * Handles Request objects generated by the servlet.
 * To do so, it calls the execute() method on the request
 * and hands over the ResourceManager.
 * @author Tarek Wilkening
 *
 */
public class RequestHandler {
	
	public RequestHandler() {
	}
	/**
	 * Calls the request's execute method, which will make
	 * the request execute itself.
	 * @param request object to be handled.
	 * @param session 
	 * @return response to the input request.
	 */
	public Response handleRequest(Request request, Session session) {
		ResourceManager man = new ResourceManager(session);
		return request.execute(man);
	}
}