-- MySQL Script generated by MySQL Workbench
-- Sa 18 Feb 2017 23:18:10 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PSEWS1617GoGruppe3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PSEWS1617GoGruppe3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PSEWS1617GoGruppe3` DEFAULT CHARACTER SET utf8 ;
USE `PSEWS1617GoGruppe3` ;

-- -----------------------------------------------------
-- Table `PSEWS1617GoGruppe3`.`gpsobject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PSEWS1617GoGruppe3`.`gpsobject` ;

CREATE TABLE IF NOT EXISTS `PSEWS1617GoGruppe3`.`gpsobject` (
  `gps_id` INT(11) NOT NULL AUTO_INCREMENT,
  `longitude` FLOAT(100,14) NULL DEFAULT NULL,
  `latitude` FLOAT(100,14) NULL DEFAULT NULL,
  `timestamp` BIGINT(64) NULL DEFAULT NULL,
  PRIMARY KEY (`gps_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSEWS1617GoGruppe3`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PSEWS1617GoGruppe3`.`users` ;

CREATE TABLE IF NOT EXISTS `PSEWS1617GoGruppe3`.`users` (
  `device_id` VARCHAR(64) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `gpsobject_gps_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`device_id`),
  INDEX `fk_users_gpsobject1_idx` (`gpsobject_gps_id` ASC),
  CONSTRAINT `fk_users_gpsobject1`
    FOREIGN KEY (`gpsobject_gps_id`)
    REFERENCES `PSEWS1617GoGruppe3`.`gpsobject` (`gps_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSEWS1617GoGruppe3`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PSEWS1617GoGruppe3`.`appointment` ;

CREATE TABLE IF NOT EXISTS `PSEWS1617GoGruppe3`.`appointment` (
  `ap_id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `gpsobject_gps_id` INT(11) NOT NULL,
  PRIMARY KEY (`ap_id`),
  INDEX `fk_appointment_gpsobject1_idx` (`gpsobject_gps_id` ASC),
  CONSTRAINT `fk_appointment_gpsobject1`
    FOREIGN KEY (`gpsobject_gps_id`)
    REFERENCES `PSEWS1617GoGruppe3`.`gpsobject` (`gps_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSEWS1617GoGruppe3`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PSEWS1617GoGruppe3`.`groups` ;

CREATE TABLE IF NOT EXISTS `PSEWS1617GoGruppe3`.`groups` (
  `group_name` VARCHAR(64) NOT NULL,
  `appointment_ap_id` INT(11) NOT NULL,
  PRIMARY KEY (`group_name`),
  INDEX `fk_groups_appointment1_idx` (`appointment_ap_id` ASC),
  CONSTRAINT `fk_groups_appointment1`
    FOREIGN KEY (`appointment_ap_id`)
    REFERENCES `PSEWS1617GoGruppe3`.`appointment` (`ap_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSEWS1617GoGruppe3`.`membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PSEWS1617GoGruppe3`.`membership` ;

CREATE TABLE IF NOT EXISTS `PSEWS1617GoGruppe3`.`membership` (
  `mem_id` INT(11) NOT NULL AUTO_INCREMENT,
  `is_admin` TINYINT NULL DEFAULT NULL,
  `is_go` TINYINT NULL DEFAULT NULL,
  `device_id` VARCHAR(64) NULL DEFAULT NULL,
  `group_name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`mem_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSEWS1617GoGruppe3`.`users_membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PSEWS1617GoGruppe3`.`users_membership` ;

CREATE TABLE IF NOT EXISTS `PSEWS1617GoGruppe3`.`users_membership` (
  `mem_id` INT(11) NOT NULL,
  `users_device_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`mem_id`, `users_device_id`),
  INDEX `fk_membership_1` (`mem_id` ASC),
  INDEX `fk_users_membership_users1_idx` (`users_device_id` ASC),
  CONSTRAINT `fk_membership`
    FOREIGN KEY (`mem_id`)
    REFERENCES `PSEWS1617GoGruppe3`.`membership` (`mem_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_membership_users1`
    FOREIGN KEY (`users_device_id`)
    REFERENCES `PSEWS1617GoGruppe3`.`users` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSEWS1617GoGruppe3`.`membership_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PSEWS1617GoGruppe3`.`membership_groups` ;

CREATE TABLE IF NOT EXISTS `PSEWS1617GoGruppe3`.`membership_groups` (
  `mem_id` INT(11) NOT NULL,
  `group_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`group_name`, `mem_id`),
  INDEX `fk_membership` (`mem_id` ASC),
  INDEX `fk_groups` (`group_name` ASC),
  CONSTRAINT `fk_membership_2`
    FOREIGN KEY (`mem_id`)
    REFERENCES `PSEWS1617GoGruppe3`.`membership` (`mem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups`
    FOREIGN KEY (`group_name`)
    REFERENCES `PSEWS1617GoGruppe3`.`groups` (`group_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSEWS1617GoGruppe3`.`secrets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PSEWS1617GoGruppe3`.`secrets` ;

CREATE TABLE IF NOT EXISTS `PSEWS1617GoGruppe3`.`secrets` (
  `secret` VARCHAR(64) NULL DEFAULT NULL,
  `sec_id` INT(11) NOT NULL AUTO_INCREMENT,
  `groups_group_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`sec_id`, `groups_group_name`),
  INDEX `fk_secrets_groups1_idx` (`groups_group_name` ASC),
  CONSTRAINT `fk_secrets_groups1`
    FOREIGN KEY (`groups_group_name`)
    REFERENCES `PSEWS1617GoGruppe3`.`groups` (`group_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
