-- SIMPLEUSER TABLE
DROP TABLE IF EXISTS `SimpleUser_table`;
  CREATE TABLE `SimpleUser_table` (
  `DEVICE_ID` varchar(64) NOT NULL,
  `NAME` varchar(20) DEFAULT NULL,
  `USER_ID` int(20) DEFAULT NULL,
  PRIMARY KEY (`DEVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `SimpleUser_table` (`DEVICE_ID`, `NAME`, `USER_ID`)
VALUES
     ('dummy-dev-id', 'dummy', '1337');

-- GPSOBJECT TABLE
DROP TABLE IF EXISTS `GpsObject_table`;
  CREATE TABLE `GpsObject_table` (
  `GPS_ID` int(64) NOT NULL AUTO_INCREMENT,
  `LON` float(100,14) DEFAULT NULL,
  `LAT` float(100,14) DEFAULT NULL,
  `TIM` long DEFAULT NULL,
  PRIMARY KEY (`GPS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `GpsObject_table` (`GPS_ID`, `LON`, `LAT`, `TIM`)
VALUES
     ('1234567', '48.1234', '8.35264','54332412');

-- GROUP TABLE
DROP TABLE IF EXISTS `GroupServer_table`;
  CREATE TABLE `GroupServer_table` (
  `NAME` varchar(64) NOT NULL,
  PRIMARY KEY (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `GroupServer_table` (`NAME`)
VALUES
     ('dummy-group');

-- MEMBERASSOCIATION TABLE
DROP TABLE IF EXISTS `MemberAssociation_table`;
  CREATE TABLE `MemberAssociation_table` (
  `MEM_ID`   int(11) NOT NULL AUTO_INCREMENT,
  `IS_ADMIN` boolean DEFAULT NULL,
  `IS_GO` boolean DEFAULT NULL,
  PRIMARY KEY (`MEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- -- APPOINTMENT TABLE
DROP TABLE IF EXISTS `Appointment_table`;
  CREATE TABLE `Appointment_table` (
  `DATE` date DEFAULT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  `ALT_ID` varchar(64) DEFAULT NULL,
  `AP_ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`AP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

